### ISSUE TITLE
next-link generator using updated_at not changed_at

### ISSUE THREAD

**Issue by timabell** [DFE-Digital/manage-courses-backend#158]
https://github.com/DFE-Digital/manage-courses-backend/blob/633a421f40e0dae2fb1663120eb69e3daec825b4/app/controllers/concerns/next_link_header.rb#L10

**Comment by misaka** [comment]
For anyone else watching, and for @timabell tomorrow when he's forgotten why he put that here, the problem here is that providers uses this code to generate a 'next link' header using `updated_at` when it should be `changed_at`.

**Comment by timabell** [comment]
done https://github.com/DFE-Digital/manage-courses-backend/pull/163/files#diff-fbd37db29fb3c6cac18d9b8b94d7f9a0
